### ISSUE TITLE
support lock_time

### ISSUE THREAD

**Issue by ecdsa** [keepkey/python-keepkey#10]
hi, 
can you add support for lock_time, like trezor did?
https://github.com/trezor/python-trezor/issues/106

**Comment by dstanchfield** [comment]
You bet.. I'll have that added for you by Monday, does that work?

**Comment by ecdsa** [comment]
great

**Comment by pooler** [comment]
Any update on this?

**Comment by ecdsa** [comment]
I believe it was fixed in 4309baec48d65022ca8a11fa9d7de95935e5b969
