### ISSUE TITLE
Python3 Bug prevents signing multisig txs

### ISSUE THREAD

**Issue by kyuupichan** [keepkey/python-keepkey#18]
Problem is simple to reproduce:

>>> import keepkeylib.ckd_public as bip32
>>> bip32.deserialize("xpub6DF8uhdarytz3FWdA8TvFSvvAh8dP3283MY7p2V4SeE2wyWmG5mg5EwVvmdMVCQcoNJxGoWaU9DCWh89LojfZ537wTfunKau47EL2dhHKon")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/keepkeylib/ckd_public.py", line 111, in deserialize
    raise Exception("Checksum failed")
Exception: Checksum failed

The bug is tools.py/b58decode getting confused between strings and binary types.  I suggest replacing with the trezorlib implementation that I've verified works fine.

That is unlikely to be the only function in that file with such a bug; please add tests for them

**Comment by kyuupichan** [comment]
By the way, the above xpub is taken from BIP32 specification document

**Comment by ngmiller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [python-keepkey issue](https://trello.com/c/eovdivxo/33-python-keepkey-issue)

**Comment by ngmiller** [comment]
@kyuupichan I've pushed up a branch and verified the above function works in both python2 and python3. Please pull down this branch and test when you get a chance. Working on adding unit tests.

**Comment by kyuupichan** [comment]
@ngmiller I've checked out the branch and things seem fine. Multisig txs are signed fine in Electron Cash but as I point out elsewhere there is a SIGHASH_FORKID problem when sending it.  I've not had time to examine in detail, but my suspicion is a firmware bug.  It could be an Electron Cash bug too though.  If you want to know how to reproduce that I can write an explanation.

**Comment by kyuupichan** [comment]
Are you certain multisig txs are being signed with SIGHASH_FORKID when the coin is BCH?

**Comment by ngmiller** [comment]
@kyuupichan We are looking into the SIGHASH_FORKID as a separate issue, since the specific function you mentioned in this issue has been addressed. I am working on this today.
