### ISSUE TITLE
"No module named rlp"

### ISSUE THREAD

**Issue by mining-visualizer** [keepkey/python-keepkey#22]
I'm trying to use the `ethereum_sign_tx` command, but when I run it, I get

```
Traceback (most recent call last):
  File "keepkeyctl", line 502, in <module>
    main()
  File "keepkeyctl", line 494, in main
    res = args.func(cmds, args)
  File "keepkeyctl", line 129, in ethereum_sign_tx
    import rlp
ImportError: No module named rlp
```

By rearranging the order of the import commands, I notice that the `ethjsonrpc` library is missing also.  Do I need to install these separately?  I just followed the install directions in the readme.  I'm running Windows 10, but am seeing the same issue in Ubuntu

**Comment by keepkeyjon** [comment]
There were a few missing dependencies in `setup.py`... should be fixed in https://github.com/keepkey/python-keepkey/commit/98acc78b2ad9a1254fcabe0d5cc50c22c6e3551e
