### ISSUE TITLE
protobuf files are compiled for python2

### ISSUE THREAD

**Issue by SomberNight** [keepkey/python-keepkey#24]
Since at least https://github.com/keepkey/python-keepkey/commit/79854bfb82455751c667fdd525338a5a1e3b586c, the included pb2 files are build for python 2.

`unicode` is undefined in python 3
https://github.com/keepkey/python-keepkey/blob/f0458664853aa7fbe0c31064d2cdda41cceec1b3/keepkeylib/messages_pb2.py#L464

**Comment by keepkeyjon** [comment]
Fixed in https://github.com/keepkey/python-keepkey/commit/acee1ed71d73c102ec1a2aef97c6fccefe2c5552
