### ISSUE TITLE
get_tx() not needed in many cases

### ISSUE THREAD

**Issue by kyuupichan** [keepkey/python-keepkey#41]
Your library should not need to call get_tx to get prior transactions for those coins that commit to their previous inputs, such as BCH abd BSV now do.  Trezor does not require previous input data any more.

Is there some dummy value I can return from get_tx() instead?

**Comment by keepkeyjon** [comment]
Agreed. We'll look into it.

**Comment by keepkeyjon** [comment]
@kyuupichan fix for this here: https://github.com/keepkey/python-keepkey/pull/54, please take a look.

**Comment by kyuupichan** [comment]
Thanks; it looks good at a glance.  I'll update ElectrumSV when you ship new libs.
