### ISSUE TITLE
PIN requested twice unnecessarily

### ISSUE THREAD

**Issue by kyuupichan** [keepkey/python-keepkey#42]
I'm not sure if this is a library issue or a firmware issue.

When first signing a transaction I'm asked to input my PIN and then my passphrase, when the device presumably sets itself up for the wallet.  I'm then immediately asked to input my PIN again to sign the transaction.  Since the PIN was requested immediately before, it should not need to ask again.  Trezor does not, for example.

**Comment by keepkeyjon** [comment]
This is a feature, not a bug. With default settings, KeepKey asks for the PIN once on the first time the host asks for something that involves seed derivation, and again every time a transaction is made. (It will also forget the PIN after the screensaver starts up).

 Enable 'Pin Caching' policy using ApplyPolicies to get the Trezor behavior.

**Comment by kyuupichan** [comment]
Thanks Jon, I wasn't aware of this feature.  I may add the ability to enable it to ElectrumSV's GUI.

Can you explain what invalidates the cached pin?  This is important to understand to be able to explain to the user in the GUI.

**Comment by keepkeyjon** [comment]
Unplugging (of course), sending the `ClearSession` message, and sitting idle on the home screen for more than `auto_lock_delay_ms` (changeable in `ApplySettings`, default is 10 mins, minimum 30 seconds). Also, fyi, the passphrase gets evicted by this too.
