### ISSUE TITLE
Invalid proto descriptor for file "types.proto"

### ISSUE THREAD

**Issue by ulrichard** [keepkey/python-keepkey#5]
After upgrading to Ubuntu 16.10, I cannot start electrum. 
With previous ubuntu versions it worked great.

This is the console output I get: 

self.keystores[name] = load_keystore(self.storage, name)
  File "/home/richi/sourcecode/electrum/lib/keystore.py", line 611, in load_keystore
    k = hardware_keystore(d)
  File "/home/richi/sourcecode/electrum/lib/keystore.py", line 595, in hardware_keystore
    return constructor(d)
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 167, in dynamic_constructor
    return self.get_plugin(name).keystore_class(d)
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 175, in get_plugin
    self.load_plugin(name)
  File "/home/richi/sourcecode/electrum/lib/plugins.py", line 100, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/home/richi/sourcecode/electrum/plugins/keepkey/keepkey.py", line 17, in **init**
    import client
  File "/home/richi/sourcecode/electrum/plugins/keepkey/client.py", line 1, in <module>
    from keepkeylib.client import proto, BaseClient, ProtocolMixin
  File "/usr/lib/python2.7/dist-packages/keepkeylib/client.py", line 15, in <module>
    from . import mapping
  File "/usr/lib/python2.7/dist-packages/keepkeylib/mapping.py", line 1, in <module>
    from . import messages_pb2 as proto
  File "/usr/lib/python2.7/dist-packages/keepkeylib/messages_pb2.py", line 12, in <module>
    import types_pb2
  File "/usr/lib/python2.7/dist-packages/keepkeylib/types_pb2.py", line 18, in <module>
    2uttonRequest_ConfirmWord\x10\x05\x12\x1c\n\x18\x42uttonRequest_WipeDevice\x10\x06\x12\x1d\n\x19\x42uttonRequest_ProtectCall\x10\x07\x12\x18\n\x14\x42uttonRequest_SignTx\x10\x08\x12\x1f\n\x1b\x42uttonRequest_FirmwareCheck\x10\t\x12\x19\n\x15\x42uttonRequest_Address\x10\n\x12\x1f\n\x1b\x42uttonRequest_FirmwareErase\x10\x0b\x12_\n&ButtonRequest_ConfirmTransferToAccount\x10\x0c\x12+\n\'ButtonRequest_ConfirmTransferToNodePath\x10\r\x12\x1d\n\x19\x42uttonRequest_ChangeLabel\x10\x0e\x12 \n\x1c\x42uttonRequest_ChangeLanguage\x10\x0f\x12\"\n\x1e\x42uttonRequest_EnablePassphrase\x10\x10\x12#\n\x1f\x42uttonRequest_DisablePassphrase\x10\x11\x12\'\n#ButtonRequest_EncryptAndSignMessage\x10\x12\x12 \n\x1c\x42uttonRequest_EncryptMessage\x10\x13\x12\"\n\x1e\x42uttonRequest_ImportPrivateKey\x10\x14\x12(\n$ButtonRequest_ImportRecoverySentence\x10\x15\x12\x1e\n\x1a\x42uttonRequest_signIdentity\x10\x16\x12\x16\n\x12\x42uttonRequest_Ping\x10\x17\x12\x1b\n\x17\x42uttonRequest_RemovePIN\x10\x18\x12\x1b\n\x17\x42uttonRequest_ChangePIN\x10\x19\x12\x1b\n\x17\x42uttonRequest_CreatePIN\x10\x1a\x12!\n\x1d\x42uttonRequest_GenerateEntropy\x10\x1b\x12\x1d\n\x19\x42uttonRequest_SignMessage\x10\x1c_\x7f\n\x14PinMatrixRequestType\x12 \n\x1cPinMatrixRequestType_Current\x10\x01\x12!\n\x1dPinMatrixRequestType_NewFirst\x10\x02\x12\"\n\x1ePinMatrixRequestType_NewSecond\x10\x03:4\n\x07wire_in\x12!.google.protobuf.EnumValueOptions\x18\xd2\x86\x03 \x01(\x08:5\n\x08wire_out\x12!.google.protobuf.EnumValueOptions\x18\xd3\x86\x03 \x01(\x08::\n\rwire_debug_in\x12!.google.protobuf.EnumValueOptions\x18\xd4\x86\x03 \x01(\x08:;\n\x0ewire_debug_out\x12!.google.protobuf.EnumValueOptions\x18\xd5\x86\x03 \x01(\x08\x42*\n\x1b\x63om.keepkey.device-protocolB\x0bKeepKeyType')
  File "/usr/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 827, in **new**
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "types.proto":
  types.proto: A file with this name is already in the pool.

**Comment by ulrichard** [comment]
This is still the single one problem stopping me from upgrading to Ubuntu 16.10 on my remaining devices.
To me it appears as if I would have to remove the type definition from the global pool, before inserting it again. But I have no experience with this whatsoever.

**Comment by ngmiller** [comment]
Hi @ulrichard. Doing some repo maintenance today. Is still an issue for you? Have you tried the latest release `4.0.2`?

**Comment by ulrichard** [comment]
Yes, this problem is still very much an issue.
I can even reproduce it in a docker container of debian:unstable if I don't use the deb package, but install the keepkey lib from pip.

**Comment by ulrichard** [comment]
Yes, this problem is still very much an issue.
I can even reproduce it in a docker container of debian:unstable if I don't use the deb package, but install the keepkey lib from pip.

**Comment by ulrichard** [comment]
I think I found part of the problem.
It seems to be an incompatibility with python-trezor.
But I need to be able to have them both installed at the same time.

**Comment by ngmiller** [comment]
@ulrichard Can you post logs that lead you to believe that's the case? If so, is it possible to install them separately into their own virtual environments for now until we resolve the conflict?

**Comment by ulrichard** [comment]
I will clean up the Dockerfile, and attach it here.
As soon as I omit the installation of either  python-trezor or python-keepkey, the error disappears and electrum starts. But then it can't load the multisig wallet that has multiple hardware wallets.
I'm not really familiar with python virtual envs, but I don't think that solves my problem.

**Comment by ulrichard** [comment]
[Dockerfile.txt](https://github.com/keepkey/python-keepkey/files/1577087/Dockerfile.txt)
[electron-cash.sh.txt](https://github.com/keepkey/python-keepkey/files/1577088/electron-cash.sh.txt)

If you enable the line with trezor in the attached Dockerfile, you will get the error.

**Comment by ngmiller** [comment]
Hi @ulrichard. Can you please reattach those files as github gists? (https://gist.github.com)

**Comment by ulrichard** [comment]
https://gist.github.com/ulrichard/67c2528b6b16806777b33c119c980b28

https://gist.github.com/ulrichard/b21452ea75fd04a14ff366e88bf1a139

**Comment by keepkeyjon** [comment]
thanks for following up
