### ISSUE TITLE
Product ID?

### ISSUE THREAD

**Issue by kyuupichan** [keepkey/python-keepkey#60]
I've just updated to the latest firmware and client library.

keepkeylib.transport_hid.DEVICE_IDS is [(11044, 1)]

However my hardware is now reporting its product_id (the 1 above) as 2.

Is this a bug?  What is the significance of 1 and 2?

**Comment by keepkeyjon** [comment]
We had to change the productId with the change over to WebUsb/WinUsb in v6.0.0 because of the way Windows caches the usb descriptors. You need to use transport_webusb with v6.0.0 and later firmwares, and transport_hid with everything earlier.

**Comment by keepkeyjon** [comment]
Additional reference: https://github.com/keepkey/keepkey-firmware/commit/97ab8b8373c8311bf4fa41f91205dc3f59437c9d
