### ISSUE TITLE
Unknow bootloader. Contact support

### ISSUE THREAD

**Issue by man22hk** [keepkey/python-keepkey#63]
Keep key show "Unknow bootloader. Contact support"

I've tried to use Centos7 with python to wipe it over HID

`[root@localhost /]# keepkeyctl wipe_device`
`No transport specified, attempting to detect device...`
`Device detected over HID`
`Device wiped`

After replug  the keepkey. Message  "Unknow bootloader. Contact support" show again.

**Comment by keepkeyjon** [comment]
Mind pasting the output of `keepkeyctl get_features`?

I think you need to update your bootloader and firmware.

**Comment by keepkeyjon** [comment]
Also, if you install the udev rules, you don't need to be root to communicate with the device.

https://github.com/keepkey/keepkey-firmware/blob/master/docs/Host.md#linux

**Comment by man22hk** [comment]
I can use this command --> keepkeyctl get_features . Please see below output : 
I also want to update the bootloader and firmware. Do you have instruction. ((As keepkey can't connected by Chrome ext. that's why I tried to use centos command mode))

FYI 
Actually, I tried to upgrade the firmware by # keepkeyctl firmware_update and success. But when I plugin the keepkey again. It said : "Unknow bootloader. Contact support"





====================================================
[root@localhost ~]# keepkeyctl get_features
No transport specified, attempting to detect device...
Device detected over HID
vendor: "keepkey.com"
major_version: 1
minor_version: 1
patch_version: 0
bootloader_mode: true
bootloader_hash: "\210\354?\352\237\003\232\024j<U\323\202\217\306~\357\352\025:                                                                                                                     \344\251&\323z\265m\266\030\327\362s"
policies {
  policy_name: "bl_debug_link"
  enabled: false
}
model: "K1-14AM"
firmware_hash: "a\301W\247\373\302/M\230%\220\232\300g\'z\224\344L\027Nw\333A\23                                                                                                                     7\273x\263a\373\364\352"
====================================================

**Comment by keepkeyjon** [comment]
> bootloader_hash: "88ec3fea9f039a146a3c55d3828fc67eefea153ae4a926d37ab56db618d7f273"

v1.1.0 bootloader's hash should start with `e45f587f...`. Can you tell me a little bit of history on this device? Have you updated its bootloader before?

**Comment by man22hk** [comment]
I don't know the bootloader_hash pattern. 
I've tried a lot time to upgrade the Keepkey by keepkeyctl and chrome ext. but fail.
You may check the mail with me to Ryan Roi (KeepKey) on Apr 12, 2:48 PM MDT for detail. request (237237) with email subject "[ShapeShift] Re: Unknown bootloader"

So , you means this keepkey with a wrong bootloader? How can I fix it?

**Comment by man22hk** [comment]
Sorry for ask again. May I have the guide of how to upgrade / reset bootloader?

**Comment by keepkeyjon** [comment]
It means your KeepKey has a bootloader that we've never seen before.  It can't be upgraded, since it wasn't a bootloader we shipped (upgrading things we don't recognize is a security risk to all of our other customers).

I'll work with support and see if we can get you a replacement.

**Comment by jverce** [comment]
Hello,

I am having a similar issue. In all cases, I updated either the firmware or the bootloader using the build artifacts obtained after building [keepkey-firmware](https://github.com/keepkey/keepkey-firmware) on my end:

### Updating the firmware
```bash
$ pwd
~/keepkey-firmware/bin
$ keepkeyctl firmware_update -f ./firmware.keepkey.bin 
...
```

### Updating the bootloader
```bash
$ keepkeyctl firmware_update -f ./blupdater.bin
```

### Output from `keepkeyctl get_features`
```
vendor: "keepkey.com"
major_version: 2
minor_version: 1
patch_version: 0
bootloader_mode: true
bootloader_hash: "\350\330x\213\331\255j,\345\366\341\"F\323b\023\345\211\022;\355)X$q\005\330\271\233\227\220\200"
policies {
  policy_name: "bl_debug_link"
  enabled: false
}
model: "K1-14AM"
firmware_hash: "\205\244O\030r\264\264\355\r_\360bq\034\375MMi\331\'C\022\311\343x\013}\270\332\220r\350"
```

**Comment by fredy314** [comment]
have same issue. is there decision ?

**Comment by fredy314** [comment]
i have build last firmware from https://github.com/keepkey/keepkey-firmware
and Output from keepkeyctl get_features
`
vendor: "keepkey.com"
major_version: 2
minor_version: 1
patch_version: 4
bootloader_mode: true
bootloader_hash: "\376\230EN~\275J\357Jm\265\275L`\365,\363\365\213\227B\203\247\301\341\374\305\376\240,\363\353"
policies {
  policy_name: "bl_debug_link"
  enabled: false
}
model: "K1-14AM"
firmware_hash: "\306\317y\347\302\314\033\234\367\354\245z\254\252\2651\013M\320\357\361U\234\3320r\225\327S%\036\377"

`
