### ISSUE TITLE
PyPI: Please update "keepkey" version (for Python 3 support)

### ISSUE THREAD

**Issue by romanz** [keepkey/python-keepkey#7]
Following #6, I would like to add correct KeepKey dependency [here](https://github.com/romanz/trezor-agent/blob/refactor-device/setup.py#L13), but the latest released [version](https://pypi.python.org/pypi/keepkey) on PyPI is 0.7.3 (from 2016-06-08). 
Could you please upload a new version of `python-keepkey` to PyPI, including the latest fixes for Python 3 compatibility?
Thanks in advance :)

**Comment by romanz** [comment]
This should allow testing https://github.com/romanz/trezor-agent/pull/70 on Python 3.x versions using Travis.

**Comment by dstanchfield** [comment]
Just want you to know we saw this..  We are pushing out a new release in about 2 weeks, and we'll make sure it's python 3 ready for you.

**Comment by romanz** [comment]
Great :)
Thanks for the update!

**Comment by romanz** [comment]
Ping?

**Comment by pkhx02** [comment]
Due to potential risk to KeepKey new feature release schedule, we have postponed the Python 3 support.  Currently, our engineers are overwhelmed with new feature implementations.  We will resume work on the Python 3 as soon as the engineers become available.

**Comment by romanz** [comment]
Sounds good, thanks for the update!

**Comment by romanz** [comment]
P.S.
The fixes needed for the package to run on Python 3 are maintained here: https://github.com/romanz/python-keepkey/commits/py3-fix

**Comment by ecdsa** [comment]
@romanz could you rebase your branch?

**Comment by romanz** [comment]
Done (at [py3-fix](https://github.com/romanz/python-keepkey/commits/py3-fix) branch):
```
$ pip3 install --user -e .
Obtaining file:///media/roman/data/roman/Code/keepkey_/python-keepkey
Requirement already satisfied: ecdsa>=0.9 in /home/roman/.local/lib/python3.5/site-packages (from keepkey==0.8.0)
Requirement already satisfied: protobuf>=2.6.1 in /home/roman/.local/lib/python3.5/site-packages (from keepkey==0.8.0)
Requirement already satisfied: mnemonic>=0.8 in /home/roman/.local/lib/python3.5/site-packages (from keepkey==0.8.0)
Requirement already satisfied: hidapi>=0.7.99.post15 in /home/roman/.local/lib/python3.5/site-packages (from keepkey==0.8.0)
Requirement already satisfied: setuptools in /home/roman/.local/lib/python3.5/site-packages (from protobuf>=2.6.1->keepkey==0.8.0)
Requirement already satisfied: six>=1.9 in /home/roman/.local/lib/python3.5/site-packages (from protobuf>=2.6.1->keepkey==0.8.0)
Requirement already satisfied: pbkdf2 in /home/roman/.local/lib/python3.5/site-packages (from mnemonic>=0.8->keepkey==0.8.0)
Installing collected packages: keepkey
  Found existing installation: keepkey 0.8.0
    Uninstalling keepkey-0.8.0:
      Successfully uninstalled keepkey-0.8.0
  Running setup.py develop for keepkey
Successfully installed keepkey
$ keepkeyctl sign_message foobar
{'address': '17SnzMuz6jxba7R3T9JVCoGnDZfUteMPvB', 'message': 'foobar', 'signature': b'HyxKj6yNDgbQdamiBJVHtC2b+8Q3WWebl9vH9UtsrZTVLo60RkhTwkUIFJUOIKBXC0MQyTLmb0vt7O1S5mcIhbw='}
```

**Comment by ecdsa** [comment]
thanks!

**Comment by ecdsa** [comment]
could you update qt/pinmatrix.py for Qt5?
all you need is copy the commit from trezorlib

**Comment by romanz** [comment]
Done -> https://github.com/romanz/python-keepkey/commit/8b8cf9b5bf7211f302b0e5640234dd915e990e9f.
Electrum seems to be working now on Python 3 :)

**Comment by ecdsa** [comment]
great, thanks! I will use your version for the release

**Comment by bgok** [comment]
An engineer is working on this now. We found that a former employee previously added the changes to support python 3, but the then removed them. We are trying to understand why they were removed before we forge ahead. Barring any major discoveries, we should be able to release the update later today.

**Comment by ecdsa** [comment]
@bgok maybe because the combined use of old protoc and "sed" is ugly, and fails on some platforms

**Comment by kyuupichan** [comment]
TX signing didn't work in Electrum 3.0 because bytes were being passed to an API expecting a string.  I've added a PR for this to @romanz branch

**Comment by ngmiller** [comment]
@romanz Can you open a PR for your python3 branch against master here? We've been testing your branch locally and most things seem to work except for the `keepkeyctl` `encrypt_message` command. We're consistently hitting this trace, resulting in `Unknown message`. Any thoughts on what might be going on here?

```
(keepkey-py-3) keepkey/python-keepkey [py3-fix●] » ./keepkeyctl encrypt_message $PUBKEY test
Traceback (most recent call last):
  File "./keepkeyctl", line 528, in <module>
    main()
  File "./keepkeyctl", line 520, in main
    res = args.func(cmds, args)
  File "./keepkeyctl", line 281, in encrypt_message
    ret = self.client.encrypt_message(pubkey, bytes(args.message, 'utf-8'), args.display_only, args.coin, address_n)
  File "/Users/nickmiller/code/keepkey/python-keepkey/keepkeylib/client.py", line 135, in wrapped_f
    ret = f(*args, **kwargs)
  File "/Users/nickmiller/code/keepkey/python-keepkey/keepkeylib/client.py", line 699, in encrypt_message
    return self.call(proto.EncryptMessage(pubkey=pubkey, message=message, display_only=display_only))
  File "/Users/nickmiller/code/keepkey/python-keepkey/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/nickmiller/code/keepkey/python-keepkey/keepkeylib/client.py", line 189, in call
    msg = handler(resp)
  File "/Users/nickmiller/code/keepkey/python-keepkey/keepkeylib/client.py", line 201, in callback_Failure
    raise CallException(msg.code, msg.message)
keepkeylib.client.CallException: (1, 'Unknown message')
```

Note, `$PUBKEY` is hex encoded.

**Comment by ngmiller** [comment]
Nevermind, we determined the firmware is not supporting those message types anymore, even though they are still included in the protobuf specs

**Comment by ngmiller** [comment]
Python3 support has been merged. Got another small PR we need to make and we'll be ready for a release candidate tag
