### ISSUE TITLE
Missing copyright headers from source files

### ISSUE THREAD

**Issue by prusnak** [keepkey/python-keepkey#9]
This fork of python-trezor is missing copyright headers from source files. See the following files for examples how headers should look like:

* https://github.com/trezor/python-trezor/blob/master/trezorctl
* https://github.com/trezor/python-trezor/blob/master/trezorlib/client.py
* https://github.com/trezor/python-trezor/blob/master/tests/device_tests/test_basic.py

**Comment by bgok** [comment]
The headers weren't there when we pulled from the python-trezor repository. We are happy to add them, though. Give us a few days because we still have github locked down after the Christmas day hack. The github accounts were never affected, but we are being abundantly cautious.

Thanks.
